main/urls.py
from django.urls import path
from main.views import show_main, create_product_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, show_table, create_product_entry_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('show-table', show_table, name='show_table'),
    path('create-product-entry', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create_product_entry_ajax', create_product_entry_ajax, name='create_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    
]

raringo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    time = models.DateField(auto_now_add=True)
    tags = models.CharField(max_length=255)
    ratings = models.DecimalField(max_digits=2, decimal_places=1)
    image_url = models.URLField(blank=True, null=True)

    @property
    def recommend_to_user(self):
        return self.ratings >= 3.7
    

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductEntryForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "tags", "ratings", "image_url"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_price(self):
        price = self.cleaned_data["price"]
        return strip_tags(price)
    
    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

    def clean_tags(self):
        tags = self.cleaned_data["tags"]
        return strip_tags(tags)
    
    def clean_ratings(self):
        ratings = self.cleaned_data["ratings"]
        return strip_tags(ratings)
    
    def clean_image_url(self):
        image_url = self.cleaned_data["image_url"]
        return strip_tags(image_url)

main/views.py
import datetime
import json
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.shortcuts import render, redirect  
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

from django.utils.html import strip_tags

from main.forms import ProductEntryForm
from main.models import Product

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST


@login_required(login_url='/login')
def show_main(request):
    context = {
        'name' : request.user.username,
        'npm' : '2306165736',
        'class' : 'PBP A',
        'application' : 'Raringo',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def show_table(request):
    context = {
        'name' : request.user.username,
        'npm' : '2306165736',
        'class' : 'PBP A',
        'application' : 'Raringo',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "table.html", context)

def create_product_entry(request):

    form = ProductEntryForm(request.POST or None)
    
    if form.is_valid() and request.method == "POST":
        product_entry = form.save(commit=False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')

    context = {
        'application': 'Raringo',
        'form': form
    }
    return render(request, "create_product_entry.html", context)

@csrf_exempt
@require_POST
def create_product_entry_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = strip_tags(request.POST.get("price"))
    description = strip_tags(request.POST.get("description"))
    time = strip_tags(request.POST.get("time"))
    tags = strip_tags(request.POST.get("tags"))
    ratings = strip_tags(request.POST.get("ratings"))
    image_url = strip_tags(request.POST.get("image_url"))
    user = request.user

    new_product = Product(
        name=name, price=price,
        description=description,
        time=time,
        tags=tags,
        ratings=ratings,
        image_url=image_url,
        user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

def edit_product(request, id):
    product_from_id = Product.objects.get(pk = id)
    product_form = ProductEntryForm(request.POST or None, instance=product_from_id)

    if product_form.is_valid() and request.method == "POST":
        product_form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': product_form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product_from_id = Product.objects.get(pk = id)
    product_from_id.delete()

    return HttpResponseRedirect(reverse('main:show_main'))

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data =  Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, "Invalid username or password. Please try again.")

    else:
       form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

@csrf_exempt
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=data["price"],
            description=data["description"],
            time=data["time"],
            tags=data["tags"],
            ratings=float(data["ratings"]),
            image_url=data["image_url"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

main/templates/card_info.html
<div class="bg-indigo-900 w-full rounded-lg font-[sans-serif] overflow-hidden w-full mx-auto">
    <div class="grid md:grid-cols-2 lg:grid-cols-3 items-center text-white">
        <div class="lg:col-span-2 p-10">
            <h1 class="text-3xl font-bold">Welcome, {{name}}</h1>
            <p class="mt-4 text-sm leading-relaxed silkscreen-regular">with NPM {{npm}} from {{class}}</p>
            <div class="flex mt-4">
                <a href="{% url 'main:create_product_entry' %}" class="btn bg-indigo-400 hover:bg-indigo-600 text-white font-bold py-2 px-4 mr-2 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
                  Add New Product
                </a>
                <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-indigo-400 hover:bg-indigo-600 text-white font-bold py-2 px-4 mr-2 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
                  Add New Product Entry by AJAX
                </button>
            </div>
        </div>
    </div>
</div>

main/templates/card_product.html
<div class="bg-white shadow-[0_4px_12px_-5px_rgba(0,0,0,0.4)] w-full max-w-sm rounded-lg overflow-hidden mx-auto font-[sans-serif] mt-4">
  <div class="min-h-[256px] flex items-center justify-center">
    {% if product_entry.image_url %}
      <img src="{{ product_entry.image_url }}" class="object-contain h-full w-auto" alt="{{ product_entry.name }}" />
    {% else %}
      <p class="mx-auto text-center text-gray-700">Picture Unavailable</p>
    {% endif %}
  </div>
  <div class="p-6">
    <h3 class="text-gray-800 text-xl font-bold">{{ product_entry.name }}</h3>
    <div class="flex space-x-2 mt-2">
      <span class="text-xs text-white bg-indigo-900 rounded-full px-3 py-1">{{ product_entry.tags }}</span>
      <span class="text-xs text-white bg-indigo-900 rounded-full px-3 py-1">{{ product_entry.ratings }} Stars</span>
    </div>
    <p class="mt-4 text-sm text-gray-500 leading-relaxed">{{ product_entry.description }}</p>
    <p class="mt-12 text-center text-lg text-white leading-relaxed bg-indigo-600 rounded-full silkscreen-regular">Rp.{{ product_entry.price }}</p>
    <p class="mt-4 text-sm text-gray-500 leading-relaxed">Added on {{ product_entry.time }}</p>
    <!-- Buttons for Edit and Delete -->
    <div class="flex space-x-2 justify-center mt-4">
      <a href="{% url 'main:edit_product' product_entry.pk %}" class=" inline-flex items-center bg-yellow-500 hover:bg-yellow-600 text-white rounded-full px-4 py-2 transition duration-300 shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
          <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
        </svg>
        Edit
      </a>
      <a href="{% url 'main:delete_product' product_entry.pk %}" class=" inline-flex items-center bg-red-500 hover:bg-red-600 text-white rounded-full p-4 transition duration-300 shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
        Delete
      </a>
    </div>
  </div>
</div>
  

main/templates/create_product_entry.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Add Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black">Add Product Entry</h1>
  
    <div class="bg-white shadow-md rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-indigo-900 text-white font-semibold px-6 py-3 rounded-lg hover:bg-indigo-700 transition duration-300 ease-in-out w-full">
            Add
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Raringo</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-4 mt-16 max-w-screen">
    <div class="container-fluid">
      {% include "card_info.html" with name=name npm=npm class=class %}   
    </div>
    <br>

    <div class="overflow-x-auto">
      <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
        <div id="product_entry_cards">
        </div>
        <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
          <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 border-b rounded-t">
              <h3 class="text-xl font-semibold text-gray-900">
                Add New Product Entry
              </h3>
              <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
                <span class="sr-only">Close modal</span>
              </button>
            </div>
            <!-- Modal body -->
            <div class="px-6 py-4 space-y-6 form-style">
              <form id="productEntryForm">
                <div class="mb-4">
                  <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
                  <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
                </div>
                <div class="mb-4">
                  <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
                  <input type="number" id="price" name="price" min="1" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
                </div>
                <div class="mb-4">
                  <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
                  <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Describe the product" required></textarea>
                </div>
                <div class="mb-4">
                  <label for="tags" class="block text-sm font-medium text-gray-700">Tags</label>
                  <input type="text" id="tags" name="tags" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
                </div>
                <div class="mb-4">
                  <label for="ratings" class="block text-sm font-medium text-gray-700">Ratings</label>
                  <input type="number" id="ratings" name="ratings" min="0" max="5" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
                </div>
                <div class="mb-4">
                  <label for="image_url" class="block text-sm font-medium text-gray-700">Image url</label>
                  <input type="text" id="image_url" name="image_url" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
                </div>
              </form>
            </div>
            <!-- Modal footer -->
            <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
              <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
              <button type="submit" id="submitProductEntry" form="productEntryForm" class="bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="flex justify-center mt-16">      
      <h5>Sesi terakhir login: {{ last_login }}</h5>
      <br />
    </div>

  </div>
</div>

<script>
    function addProductEntry() {
    fetch("{% url 'main:create_product_entry_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#productEntryForm')),
    })
    .then(response => refreshProductEntries())

    document.getElementById("productEntryForm").reset(); 
    document.querySelector("[data-modal-toggle='crudModal']").click();

    return false;
  }

  async function getProductEntries(){
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshProductEntries() {
    document.getElementById("product_entry_cards").innerHTML = "";
    document.getElementById("product_entry_cards").className = "";
    const productEntries = await getProductEntries();
    let htmlString = "";
    let classNameString = "";

    if (productEntries.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <img src="https://www.svgrepo.com/show/525569/upload-minimalistic.svg" alt="No Product Added" class="w-32 h-32 mb-4"/>
                <p class="text-center text-gray-600 mt-4">Please, add at least one product.</p>
            </div>
        `;
    }
    else {
        classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full"
        productEntries.forEach((item) => {
            const name = DOMPurify.sanitize(item.fields.name);
            const price = DOMPurify.sanitize(item.fields.price);
            const description = DOMPurify.sanitize(item.fields.description);
            const tags = DOMPurify.sanitize(item.fields.tags);
            const ratings = DOMPurify.sanitize(item.fields.ratings);
            const time = DOMPurify.sanitize(item.fields.time);
            const image_url = DOMPurify.sanitize(item.fields.image_url);
            htmlString += `
            <div class="relative break-inside-avoid">
              <div class="bg-white shadow-[0_4px_12px_-5px_rgba(0,0,0,0.4)] w-full max-w-sm rounded-lg overflow-hidden mx-auto font-[sans-serif] mt-4">
                <div class="min-h-[256px] flex items-center justify-center">
                    <img src="${image_url}" class="object-contain h-full w-auto" alt="${name}" />
                </div>
                <div class="p-6">
                  <h3 class="text-gray-800 text-xl font-bold">${name}</h3>
                  <div class="flex space-x-2 mt-2">
                    <span class="text-xs text-white bg-indigo-900 rounded-full px-3 py-1">${tags}</span>
                    <span class="text-xs text-white bg-indigo-900 rounded-full px-3 py-1">${ratings} Stars</span>
                  </div>
                  <p class="mt-4 text-sm text-gray-500 leading-relaxed">${description}</p>
                  <p class="mt-12 text-center text-lg text-white leading-relaxed bg-indigo-600 rounded-full silkscreen-regular">Rp.${price}</p>
                  <p class="mt-4 text-sm text-gray-500 leading-relaxed">Added on ${time}</p>
                  <!-- Buttons for Edit and Delete -->
                  <div class="flex space-x-2 justify-center mt-4">
                    <a href="/edit-product/${item.pk}" class=" inline-flex items-center bg-yellow-500 hover:bg-yellow-600 text-white rounded-full px-4 py-2 transition duration-300 shadow-md">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                      </svg>
                      Edit
                    </a>
                    <a href="/delete/${item.pk}" class=" inline-flex items-center bg-red-500 hover:bg-red-600 text-white rounded-full p-4 transition duration-300 shadow-md">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                      </svg>
                      Delete
                    </a>
                  </div>
                </div>
              </div>
            </div>
            `;
        });
    }
    document.getElementById("product_entry_cards").className = classNameString;
    document.getElementById("product_entry_cards").innerHTML = htmlString;
}
refreshProductEntries();

    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    function showModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modal.classList.remove('hidden'); 
        setTimeout(() => {
          modalContent.classList.remove('opacity-0', 'scale-95');
          modalContent.classList.add('opacity-100', 'scale-100');
        }, 50); 
    }

    function hideModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');

        modalContent.classList.remove('opacity-100', 'scale-100');
        modalContent.classList.add('opacity-0', 'scale-95');

        setTimeout(() => {
          modal.classList.add('hidden');
        }, 150); 
    }

    document.getElementById("cancelButton").addEventListener("click", hideModal);
    document.getElementById("closeModalBtn").addEventListener("click", hideModal);

    document.getElementById("productEntryForm").addEventListener("submit", (e) => {
      e.preventDefault();
      addProductEntry();
    })
  
</script>

{% endblock content %}

main/templates/table.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Raringo</title>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-4 mt-16 max-w-screen">
    <div class="container-fluid">
      {% if not product_entries %}
      <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
        <img src="https://www.svgrepo.com/show/479352/gear.svg" alt="Under Construction" class="w-32 h-32 mb-4"/>
        <p class="text-center text-gray-600 mt-4">Under Construction due to AJAX Implmentation</p>
    </div>
      {% else %}
      <table class="min-w-full bg-white rounded-lg border border-gray-200">
        <thead class="bg-indigo-900 text-white">
          <tr>
            <th class="text-left py-3 px-4 font-semibold text-sm border-b border-gray-300">Product Name</th>
            <th class="text-left py-3 px-4 font-semibold text-sm border-b border-gray-300">Price</th>
            <th class="text-left py-3 px-4 font-semibold text-sm border-b border-gray-300">Description</th>
            <th class="text-left py-3 px-4 font-semibold text-sm border-b border-gray-300">Tags</th>
            <th class="text-left py-3 px-4 font-semibold text-sm border-b border-gray-300">Ratings</th>
            <th class="text-left py-3 px-4 font-semibold text-sm border-b border-gray-300">Time Ordered</th>
            <th class="text-left py-3 px-4 font-semibold text-sm border-b border-gray-300"></th>
            <th class="text-left py-3 px-4 font-semibold text-sm border-b border-gray-300"></th>
          </tr>
        </thead>
        <tbody class="text-gray-700">
          {% for product_entry in product_entries %}
          <tr>
            <td class="py-3 px-4 border-b border-gray-300">{{product_entry.name}}</td>
            <td class="py-3 px-4 border-b border-gray-300">Rp{{product_entry.price}}</td>
            <td class="py-3 px-4 border-b border-gray-300">{{product_entry.description}}</td>
            <td class="py-3 px-4 border-b border-gray-300">{{product_entry.tags}}</td>
            <td class="py-3 px-4 border-b border-gray-300">{{product_entry.ratings}} Stars</td>
            <td class="py-3 px-4 border-b border-gray-300">{{product_entry.time}}</td>
            <td class="text-blue-600 hover:underline border-b border-gray-300 py-3 px-4">
              <a href="{% url 'main:edit_product' product_entry.pk %}">
                  <button>
                      Edit
                  </button>
              </a>
            </td>
            <td class="text-blue-600 hover:underline border-b border-gray-300 py-3 px-4">
              <a href="{% url 'main:delete_product' product_entry.pk %}">
                  <button>
                      Delete
                  </button>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% endif %}
    </div>

    <div class="flex justify-center mt-4">
      <a href="{% url 'main:create_product_entry' %}" class="btn bg-indigo-400 hover:bg-indigo-600 text-white font-bold py-2 px-4 mr-2 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
        Add New Product
      </a>
    </div>

    <div class="flex justify-center mt-16">      
      <h5>Sesi terakhir login: {{ last_login }}</h5>
      <br />
    </div>
  </div>
</div>

{% endblock content %}